---
title: Hisamuka.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: samuel.martins@ifsp.edu.br
location: Campinas, Brazil
social_networks:
- name: Linkedin
  link: https://www.linkedin.com/in/samuel-botter-martins
  badge: https://img.shields.io/badge/-LinkedIn-306EA8?style=flat&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/samuel-botter-martins
  icon: <i class="fab fa-fw fa-linkedin" aria-hidden="true"></i>
  show_sidebar: true
- name: Twitter
  link: https://twitter.com/hisamuka
  badge: https://img.shields.io/badge/-Twitter-4B9AE5?style=flat&amp;logo=Twitter&amp;logoColor=white&amp;link=https://twitter.com/hisamuka
  icon: <i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i>
  show_sidebar: true
- name: GitHub
  link: https://github.com/hisamuka
  badge: https://img.shields.io/badge/-GitHub-2F2F2F?style=flat&logo=github&logoColor=white&link=https://github.com/hisamuka
  icon: <i class="fab fa-fw fa-github" aria-hidden="true"></i>
  show_sidebar: true
- name: YouTube
  link: https://www.youtube.com/xavecoding
  badge: https://img.shields.io/youtube/channel/subscribers/UCICVlpgW9gVd0UXbOALDFaQ?label=YouTube&style=social
  icon: <i class="fab fa-brands fa-youtube" aria-hidden="true"></i>
  show_sidebar: true
- name: Google Scholar
  link: https://scholar.google.com.br/citations?user=f6Cc4nUAAAAJ&hl
  badge: https://img.shields.io/badge/-Google_Scholar-676767?style=flat&logo=google-scholar&logoColor=white&link=https://scholar.google.com.br/citations?user=f6Cc4nUAAAAJ&hl=en
  icon: ''
  show_sidebar: false
disqus:
  shortname: https-hisamuka-github-io
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      comments: true   # change to false to default to comments off site-wide