---
# for SEO purposes
title: Samuel B. Martins (Samuka) logbook
title_separator: "-"
subtitle: A website about me and posts on ML
name: Samuel Botter Martins (Samuka)
description: A website that works as my logbook, hosting my blog, with ML and computing tutorials, research, portfolio, teaching notes, and other general stuff
url: https://hisamuka.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
teaser: /assets/images/website-thumbnail.png  # path of fallback teaser image, e.g. "/assets/images/500x300.png"

author:
  name: Samuel Botter Martins (Samuka)
  avatar: /assets/images/website-thumbnail.png # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: I am an assistant professor, data scientist, researcher, and YouTube creator.
  location: Campinas, Brazil
  email: samuel.martins@ifsp.edu.br
  twitter: hisamuka
  links:
    - label: Linkedin
      url: https://www.linkedin.com/in/samuel-botter-martins
      badge: https://img.shields.io/badge/-LinkedIn-306EA8?style=flat&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/samuel-botter-martins
      icon: <i class="fab fa-fw fa-linkedin" aria-hidden="true"></i>
      show_sidebar: true
    - label: Twitter
      url: https://twitter.com/hisamuka
      badge: https://img.shields.io/badge/-Twitter-4B9AE5?style=flat&amp;logo=Twitter&amp;logoColor=white&amp;link=https://twitter.com/hisamuka
      icon: <i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i>
      show_sidebar: true
    - label: GitHub
      url: https://github.com/hisamuka
      badge: https://img.shields.io/badge/-GitHub-2F2F2F?style=flat&logo=github&logoColor=white&link=https://github.com/hisamuka
      icon: <i class="fab fa-fw fa-github" aria-hidden="true"></i>
      show_sidebar: true
    - label: YouTube
      url: https://www.youtube.com/xavecoding
      badge: https://img.shields.io/youtube/channel/subscribers/UCICVlpgW9gVd0UXbOALDFaQ?label=YouTube&style=social
      icon: <i class="fab fa-brands fa-youtube" aria-hidden="true"></i>
      show_sidebar: true
    - label: Google Scholar
      url: https://scholar.google.com.br/citations?user=f6Cc4nUAAAAJ&hl
      badge: https://img.shields.io/badge/-Google_Scholar-676767?style=flat&logo=google-scholar&logoColor=white&link=https://scholar.google.com.br/citations?user=f6Cc4nUAAAAJ&hl=en
      icon: ''
      show_sidebar: false

twitter:
  username: hisamuka
og_image: /assets/images/website-thumbnail.png  # Open Graph/Twitter default site image

logo: /assets/images/samuka-logo.png
social:
  name: Samuel Botter Martins
  links:
    - https://twitter.com/hisamuka
    - https://www.linkedin.com/in/samuel-botter-martins
    - https://github.com/hisamuka
    - https://www.youtube.com/xavecoding

timezone: UTC
words_per_minute: 200.0
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    
    

disqus:
  shortname: https-hisamuka-github-io
 
default_post_thumbnail: "data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22316%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20316%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17f48594a84%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17f48594a84%22%3E%3Crect%20width%3D%22316%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22108.19921875%22%20y%3D%2297.35%22%3EImage%20cap%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      comments: true   # change to false to default to comments off site-wide


# https://blog.webjeda.com/jekyll-pagination/#pagination-can-be-done-only-on-indexhtml
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


paginate: 10
paginate_path: "/blog/page:num/"


